#ifndef __TIMER_DEFINES_H__
#define __TIMER_DEFINES_H__
#define TIMER_ADDRESS 0x80003000
#define TIMER_SIZE 0x1000
#define TIMER_COUNT_REG_OFFS 0x0
#define CURRENT_VALUE_OFFSET 0x0
#define CURRENT_VALUE_MASK 0xffffffff
#define CURRENT_VALUE_BITS 0x20
#define TIMER_RELOAD_REG_OFFS 0x4
#define RELOAD_VALUE_OFFSET 0x0
#define RELOAD_VALUE_MASK 0xffffffff
#define RELOAD_VALUE_BITS 0x20
#define TIMER_CONTROL_REG_OFFS 0x8
#define TIMER_ENABLED_OFFSET 0x1
#define TIMER_ENABLED_MASK 0x2
#define TIMER_ENABLED_BITS 0x1
#define TIMER_IRQ_ENABLE_OFFSET 0x2
#define TIMER_IRQ_ENABLE_MASK 0x4
#define TIMER_IRQ_ENABLE_BITS 0x1
#define TIMER_PERIODIC_OFFSET 0x0
#define TIMER_PERIODIC_MASK 0x1
#define TIMER_PERIODIC_BITS 0x1
#define TIMER_EOI_REG_OFFS 0xc
#endif /* __TIMER_DEFINES_H__ */